### ISSUE TITLE
add package dependency on "dbgsym" kernel package

### ISSUE THREAD

**Issue by prakashsurya** [delphix/delphix-kernel#6]
Currently, we required the debug symbol package to be installed for our kernels, so that we can more easily debug kernel problems (e.g. with crash and the debug kernel symbols).

We install this debug symbol package "manually" via the appliance-build logic [here](https://github.com/delphix/appliance-build/blob/master/live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml#L71); i.e.
```
- shell: ls /lib/modules
  register: kernel_versions

- apt:
    name: 'linux-image-{{ item }}-dbgsym'
  with_items:
    - '{{ kernel_versions.stdout_lines }}'
  retries: 3
  delay: 30
  register: result
until: result is succeeded
```

It'd be better to remove this manual installation, and instead have the delphix-kernel package depend on the debug symbol package. This way, when installing the delphix-kernel package, it'd automatically pull in the correct debug symbol package.

This would also help ensure the correct kernel packages remain installed after I land my changes being proposed to appliance-build [here](https://github.com/delphix/appliance-build/pull/257). Currently with these proposed changes, the debug symbol package is removed on upgrade for old kernels, because it's not listed as a package dependency of any delphix-kernel package; if it was a package dependency, it'd remain installed (as it should).
